PRAGMA foreign_keys = ON;

CREATE TABLE Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT UNIQUE NOT NULL,
    HashedPassword TEXT NOT NULL
);

CREATE TABLE Chats (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    AdminId INTEGER NOT NULL,
    FOREIGN KEY (AdminId) REFERENCES Users(Id)
);

CREATE TABLE UserChats (
    UserId INTEGER NOT NULL,
    ChatId INTEGER NOT NULL,
    PRIMARY KEY (UserId, ChatId),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (ChatId) REFERENCES Chats(Id)
);

CREATE TABLE Messages (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    ChatId INTEGER NOT NULL,
    SenderId INTEGER NOT NULL,
    Timestamp TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    Content TEXT NOT NULL,
    FOREIGN KEY (ChatId) REFERENCES Chats(Id),
    FOREIGN KEY (SenderId) REFERENCES Users(Id)
);
